### DISCUSSION TITLE
Route Acexy container traffic through a Warp VPN

### DISCUSSION THREAD

**Discussion by arlequii** [Javinator9889/acexy#32] [Q&A] [answered]
I’m trying to run the Acexy container and route all its traffic through a Warp VPN container, but I’m not sure how to properly configure the networking between them.

Could you provide guidance on how to link these two containers so that Acexy’s traffic is routed through the Warp VPN container?

I appreciate any help or example configurations.

**Comment by Javinator9889** [comment]
You will need the following settings:

1. Find a Docker container giving access to the Warp VPN - I guess [gluetun](https://github.com/qdm12/gluetun) has support for it.
2. By using the project's `docker-compose.yml`, configure a network where all the containers are linked between them.
  - As of `v0.2.0`, you only need the AceStream container to be linked with the VPN provider.
3. Configure the containers to depend on each other, so you don't get spurious failures because of a race condition.

For reference, this is a small example of a configuration I've been playing with:

```yaml
services:
  acexy:
    image: ghcr.io/javinator9889/acexy:0.1.2
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy

  gluetun:
    image: gmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
```

> NOTE: That configuration is not complete, but serves for the sake of showcasing how it should be configured.

**Reply by matzeroe** [reply, marked as answer]
```yaml
services:
  acexy:
    image: ghcr.io/javinator9889/acexy:0.2.0
    # Use gluetun's network stack
    network_mode: "service:gluetun"
    depends_on:
      - acestream # Depends on acestream, which depends on gluetun
    environment:
      ACEXY_LISTEN_ADDR: ":8080"        # Listen on port 8080 (within the shared network)
      ACEXY_SCHEME: "http"
      # Connect to acestream via localhost as they share the network stack
      ACEXY_HOST: "localhost"
      ACEXY_PORT: "6878"
      ACEXY_M3U8_STREAM_TIMEOUT: "60s"
      ACEXY_M3U8: "false"
      ACEXY_EMPTY_TIMEOUT: "60s"
      ACEXY_BUFFER_SIZE: "8MB" # Ensure value is quoted if using units like MB/GB
      ACEXY_NO_RESPONSE_TIMEOUT: "10s"
    restart: unless-stopped # Added restart policy for acexy

  acestream:
    image: martinbjeldbak/acestream-http-proxy:latest 
    # Use gluetun's network stack
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    # Ports are NOT exposed here, they are exposed via gluetun if needed
    # environment:
      # Optional extra flags if needed
      # EXTRA_FLAGS: "--cache-dir /tmp --cache-limit 2 --cache-auto 1 --log-stderr --log-stderr-level error"
    restart: unless-stopped # Added restart policy for acestream

  gluetun:
    image: qmcgaw/gluetun
    # container_name: gluetun # Only needed if EXTERNAL containers connect, not needed here.
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun # Ensure mapping is correct
    ports:
      # Port for Acexy (publish the port acexy listens on internally)
      - "8080:8080/tcp"
      - "8888:8888/tcp" # HTTP proxy
      - "8388:8388/tcp" # Shadowsocks TCP
      - "8388:8388/udp" # Shadowsocks UDP
    volumes:
      - /docker/gluetun:/gluetun # Make sure this path exists on your host
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - SERVER_COUNTRIES=
      - TZ=Europe/Berlin # Correct Timezone format
      - UPDATER_PERIOD=24h
    restart: unless-stopped

```
this is a working gluetun + acexy example compose file for anyone who can´t get it to work.
