### ISSUE TITLE
Proxy stop working when try to watch an offline channel

### ISSUE THREAD

**Issue by dceldran** [Javinator9889/acexy#14]
Hi, 

First of all thanks for this project, i have a similar usecase than you and all acestream engine dockers does not have the feature to execute concurrent streams at the same time, so thanks for your job!

Well i have a .m3u file that i've created with all acestream channels that i want to use and i import this m3u file to some iptv app. With this i can watch acestream through your project in any tv on my home network.

My docker compose is like this:
```
services:
  acexy:
    image: ghcr.io/javinator9889/acexy
    restart: always
    ports:
      - "8083:8083"
      - "6877:6878"
    environment:
      ACEXY_LISTEN_ADDR: ":8083"  # Listen on port 8080
      ACEXY_SCHEME: "http"        # Use HTTP
      ACEXY_HOST: "localhost"     # Host is localhost
      ACEXY_PORT: "6878"          # Port is 6878
      ACEXY_M3U8_STREAM_TIMEOUT: "60s"  # Timeout is 60 seconds when in M3U8 mode
      ACEXY_M3U8: "false"         # Disable M3U8 mode
```

As you know, acestream channels are not always online, so i load my m3u file to vlc and i put a stream that is online and works fine but if i change channels fast and some are not online, the proxy breaks and stop works. After that i return to a channel that is online and it's not working anymore until i restart docker container. If i connect bypassing the proxy (with port 6877 in my case) acestream engine still working, but if i try to connect to the proxy (port 8083 in my case) it's not working.

I can see in the log files this:
```
WARN Failed to copy response body error="errors (1) when writing to 3 writers\nwrite tcp 192.168.96.2:8083->192.168.96.1:59900: write: broken pipe\n"
WARN Failed to copy response body error="errors (1) when writing to 1 writers\nwrite tcp 192.168.96.2:8083->192.168.96.1:53420: write: broken pipe\n"
```

The ip address `192.168.96.2` it's the ip that docker auto assign to the container and ip `192.168.96.1` it's the ip of the docker gateway.

Thanks!
