### ISSUE TITLE
[BUG] Failed to forward stream

### ISSUE THREAD

**Issue by josearregui90** [Javinator9889/acexy#30]
### Bug Description

On some streams I get the following error:

```
2025/03/05 18:20:55 INFO Started new stream id="{id: 4ce55db7e578ff52a6e526cf610e477464b8a99f}" clients=0

2025/03/05 18:20:56 ERROR Failed to forward stream error="Get \"http://localhost:6878/ace/r/58b193890946b099a7d2c7dca37a48b36a12467f/0dc8b9da69ccaee90286d7cc983eedce\": net/http: timeout awaiting response headers"

2025/03/05 18:20:56 ERROR Failed to start stream stream="{id: 4ce55db7e578ff52a6e526cf610e477464b8a99f}" error="Get \"http://localhost:6878/ace/r/58b193890946b099a7d2c7dca37a48b36a12467f/0dc8b9da69ccaee90286d7cc983eedce\": net/http: timeout awaiting response headers"
```

I tried those IDs in ghcr.io/martinbjeldbak/acestream-http-proxy and they worked well. 

### Steps to Reproduce

Docker-compose:

```
  acexy:
    image: ghcr.io/javinator9889/acexy
    container_name: acexy
    environment:
      ACEXY_LISTEN_ADDR: ":8080"  # Listen on port 8080
      ACEXY_SCHEME: "http"        # Use HTTP
      ACEXY_HOST: "localhost"     # Host is localhost
      ACEXY_PORT: "6878"          # Port is 6878
      ACEXY_M3U8_STREAM_TIMEOUT: "60s"  # Timeout is 60 seconds when in M3U8 mode
      #ACEXY_M3U8: "true"         # Disable M3U8 mode
      ALLOW_REMOTE_ACCESS: "yes"
      EXTRA_FLAGS: "--cache-limit-bytes 500000000 --live-cache-type memory --vod-cache-type memory --state-dir /dev/shm/.ACEStream --set_allow_remote_access true"

    volumes:
      - /dev/disk/by-id/:/dev/disk/by-id/:ro
    ports: 
      - 8080:8080
      - 8621:8621
    restart: unless-stopped
```

- http://192.168.10.10:8080/ace/getstream?id=4ce55db7e578ff52a6e526cf610e477464b8a99f

### Expected Behavior

Get a stream in VLC. 

### Actual Behavior

Got an error message in VLC: ```
Su entrada no puede abrirse:
VLC es incapaz de abrir el MRL «http://192.168.10.10:8080/ace/getstream?id=4ce55db7e578ff52a6e526cf610e477464b8a99f». Vea el registro para más detalles.
```

Got an error in logs: 
`2025/03/05 18:20:55 INFO Started new stream id="{id: 4ce55db7e578ff52a6e526cf610e477464b8a99f}" clients=0

2025/03/05 18:20:56 ERROR Failed to forward stream error="Get \"http://localhost:6878/ace/r/58b193890946b099a7d2c7dca37a48b36a12467f/0dc8b9da69ccaee90286d7cc983eedce\": net/http: timeout awaiting response headers"

2025/03/05 18:20:56 ERROR Failed to start stream stream="{id: 4ce55db7e578ff52a6e526cf610e477464b8a99f}" error="Get \"http://localhost:6878/ace/r/58b193890946b099a7d2c7dca37a48b36a12467f/0dc8b9da69ccaee90286d7cc983eedce\": net/http: timeout awaiting response headers"`

### Version

0.1.2

### Environment

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [x] Docker
